[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["cd cms && npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd cms && npm run build"]

[start]
cmd = "cd cms && npm run start"
